#! /usr/bin/env perl

use v5.34.0;
use strict;
use warnings;

use Getopt::Long;

sub get_random_string {
    my $length = shift || 16;
    my $str = '';

    my @chars = ('a'..'z', 'A'..'Z', '0'..'9');
    $str .= $chars[rand @chars] for 1..$length;
    return $str;
}

sub assemble {
    my $src = shift;
    my $dest = shift;
    `nasm -f bin -o $dest $src`;
}

sub preview {
    my $src = shift;
    my $dest = get_random_string;
    `nasm -f bin -o $dest $src`;
    say "$src => ", -s $dest, " bytes";
    unlink $dest or warn "Could not delete temporary file: $!\n";
}

sub assemble_with_padding {
    my $src = shift;
    my $dest = shift;
    my $padding = shift;
    my $rand = get_random_string;
    my $start_rand = "start_$rand";
    my $tmpfile = "tmp_$rand.asm";

    open my $tmpout, '>>', $tmpfile or die "Could not create temporary file: $!\n";
    open my $asm, '<', $src or die "Could not open $src: $!\n";
    say $tmpout "$start_rand:";
    while(<$asm>) {
        print $tmpout $_;
    }
    say $tmpout "times $padding - (\$ - $start_rand) db 0";
    `nasm -f bin -o $dest $tmpfile`;
    unlink $tmpfile or warn "Could not delete temporary file: $!\n";
}

sub init {
    my $src;
    my $dest;
    my $padding = 0;                # Don't pad by default
    GetOptions(
        'src=s' => \$src,
        'dest=s' => \$dest,
        'padding=i' => \$padding,
    ) or die "Error in command line arguments\n";
    
    my $subcommand = shift @ARGV;
    if($subcommand eq 'preview') {
        if($src && $dest) {
            warn "Warning: too many options provided - preview only requires the --src option.\n" 
        }
        preview $src;
    }
    elsif($subcommand eq 'assemble') {
        if($padding)    { assemble_with_padding $src, $dest, $padding; }
        else            { assemble $src, $dest }
    }
}

init;
